"""
AI-Assisted Housing Inspection Dashboard
Powered by Snowflake Cortex (llama3.1-8b)

Runs inside Snowflake Streamlit environment.
"""
import streamlit as st
from snowflake.snowpark.context import get_active_session
from datetime import datetime

# Page config
st.set_page_config(
    page_title="AI House Inspection", 
    layout="wide",
    initial_sidebar_state="expanded"
)

# Title
st.title("🏠 AI-Assisted House Inspection Dashboard")
st.markdown("*Powered by Snowflake Cortex Intelligence - AI for Good*")

# Get session
session = get_active_session()

# Sidebar - Social Impact
with st.sidebar:
    st.header("🌟 AI for Good Initiative")
    st.markdown("""
    **Mission**: Helping families and regulators spot unsafe housing earlier, 
    improving residential infrastructure safety.
    """)
    
    try:
        impact_query = """
        SELECT 
            COUNT(DISTINCT PROPERTY_ID) as total_properties,
            SUM(CASE WHEN RISK_LEVEL = 'HIGH' THEN 1 ELSE 0 END) as high_risk_properties,
            SUM(TOTAL_ISSUES) as total_issues_found
        FROM HOUSING_INSPECTION.CORE.PROPERTY_RISK_SUMMARY
        """
        impact_df = session.sql(impact_query).collect()
        if impact_df:
            st.metric("🏘️ Properties Inspected", impact_df[0]['TOTAL_PROPERTIES'])
            st.metric("🚨 High-Risk Flagged", impact_df[0]['HIGH_RISK_PROPERTIES'])
            st.metric("🔍 Total Issues Found", impact_df[0]['TOTAL_ISSUES_FOUND'])
    except:
        pass
    
    st.markdown("---")
    st.success("🤖 Using Snowflake Cortex AI\n\nllama3.1-8b model")
    st.info("💡 Early detection saves lives")

# Main tabs
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Property Dashboard", 
    "📸 New Inspection (AI-Powered)", 
    "🤖 AI Performance",
    "📋 All Properties"
])

# =====================================================
# TAB 1: Property Dashboard
# =====================================================
with tab1:
    try:
        query = """
        SELECT * FROM HOUSING_INSPECTION.CORE.STREAMLIT_DASHBOARD_VIEW
        """
        df = session.sql(query).to_pandas()
        
        if len(df) == 0:
            st.warning("⚠️ No properties found. Use 'New Inspection' tab to add data.")
        else:
            property_name = st.selectbox(
                "🏢 Select a Property",
                df["PROPERTY_NAME"].unique()
            )
            
            selected = df[df["PROPERTY_NAME"] == property_name].iloc[0]
            
            # KPIs
            st.markdown("### 📊 Property Risk Overview")
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                risk_emoji = {
                    "HIGH": "🔴",
                    "MEDIUM": "🟡",
                    "LOW": "🟢"
                }.get(selected["RISK_LEVEL"], "⚪")
                st.metric("Risk Level", f"{risk_emoji} {selected['RISK_LEVEL']}")
            
            with col2:
                st.metric("AI Risk Score", f"{int(selected['RISK_SCORE'])}")
            
            with col3:
                st.metric("Issues Detected", int(selected["TOTAL_ISSUES"]))
            
            with col4:
                st.metric(
                    "Repair Cost",
                    f"₹{int(selected['TOTAL_ESTIMATED_REPAIR_COST']):,}"
                )
            
            # AI Summary
            st.markdown("---")
            st.subheader("🧠 AI-Generated Inspection Summary")
            if selected["AI_SUMMARY"]:
                st.info(selected["AI_SUMMARY"])
                st.caption(f"Generated by {selected['CLASSIFICATION_METHOD']}")
            else:
                st.info("AI summary will appear after inspection findings are added.")
            
            # Recommendation
            st.subheader("✅ AI-Recommended Action")
            if selected["RISK_LEVEL"] == "HIGH":
                st.error(f"🚨 {selected['RECOMMENDED_ACTION']}")
            elif selected["RISK_LEVEL"] == "MEDIUM":
                st.warning(f"⚠️ {selected['RECOMMENDED_ACTION']}")
            else:
                st.success(f"✅ {selected['RECOMMENDED_ACTION']}")
            
            # Room Details
            st.markdown("---")
            st.subheader("🔍 Room-Level AI Analysis")
            
            room_query = f"""
            SELECT
                ROOM_NAME,
                ISSUE_COUNT,
                ROOM_RISK_SCORE,
                ISSUE_TYPES,
                ROOM_REPAIR_COST,
                AVG_AI_CONFIDENCE
            FROM HOUSING_INSPECTION.CORE.ROOM_RISK_VIEW
            WHERE PROPERTY_NAME = '{property_name}'
            ORDER BY ROOM_RISK_SCORE DESC
            """
            
            room_df = session.sql(room_query).to_pandas()
            if len(room_df) > 0:
                st.dataframe(
                    room_df,
                    use_container_width=True,
                    column_config={
                        "ROOM_NAME": "Room",
                        "ISSUE_COUNT": "Issues",
                        "ROOM_RISK_SCORE": "Risk Score",
                        "ISSUE_TYPES": "AI-Detected Types",
                        "ROOM_REPAIR_COST": st.column_config.NumberColumn(
                            "Repair Cost",
                            format="₹%d"
                        ),
                        "AVG_AI_CONFIDENCE": st.column_config.NumberColumn(
                            "AI Confidence",
                            format="%.0f%%"
                        )
                    }
                )
            else:
                st.info("No room data available.")
                
    except Exception as e:
        st.error(f"⚠️ Error: {e}")

# =====================================================
# TAB 2: New Inspection with Real AI
# =====================================================
with tab2:
    st.header("📸 AI-Powered Inspection Entry")
    st.markdown("**Enter findings and let Snowflake Cortex AI classify them automatically**")
    
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.subheader("Property & Room Information")
        
        property_name_input = st.text_input("Property Name", "Green View Apartments")
        city_input = st.text_input("City", "Delhi")
        room_name_input = st.text_input("Room Name", "Living Room")
        
        st.subheader("📝 Inspection Description")
        finding_text = st.text_area(
            "Describe what you observed",
            "Severe water seepage near the ceiling with visible dampness",
            height=120,
            help="Be detailed - AI will analyze this"
        )
    
    with col2:
        st.subheader("🤖 Real-Time AI Classification")
        st.caption("Using Snowflake Cortex llama3.1-8b")
        
        if st.button("🔍 Analyze with AI", type="primary", use_container_width=True):
            with st.spinner("🤖 AI is analyzing..."):
                # Use REAL Cortex AI
                classify_query = f"""
                SELECT
                  TRIM(LOWER(
                    SNOWFLAKE.CORTEX.COMPLETE(
                      'llama3.1-8b',
                      'Classify as ONE word: leak, crack, wiring, structural, or ok. Finding: {finding_text}'
                    )
                  )) as ai_label,
                  TRIM(UPPER(
                    SNOWFLAKE.CORTEX.COMPLETE(
                      'llama3.1-8b',
                      'Rate severity as ONE word: critical, high, medium, or low. Issue: {finding_text}'
                    )
                  )) as ai_severity,
                  SNOWFLAKE.CORTEX.SENTIMENT('{finding_text}') as sentiment
                """
                
                try:
                    result = session.sql(classify_query).collect()[0]
                    
                    # Extract clean labels
                    label = result['AI_LABEL']
                    for keyword in ['leak', 'crack', 'wiring', 'structural', 'ok']:
                        if keyword in label:
                            label = keyword
                            break
                    
                    severity = result['AI_SEVERITY']
                    for sev in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']:
                        if sev in severity:
                            severity = sev
                            break
                    
                    # Calculate confidence
                    confidence = int(min(95, max(65, abs(result['SENTIMENT']) * 100 + 50)))
                    
                    st.success("✅ AI Analysis Complete!")
                    
                    col_a, col_b = st.columns(2)
                    with col_a:
                        st.metric("🎯 AI Detected", label.upper())
                        st.metric("📊 Severity", severity)
                    with col_b:
                        st.metric("🤖 Confidence", f"{confidence}%")
                        
                        # Estimate cost
                        cost_map = {
                            'leak': {'CRITICAL': 100000, 'HIGH': 50000, 'MEDIUM': 25000, 'LOW': 10000},
                            'wiring': {'CRITICAL': 100000, 'HIGH': 40000, 'MEDIUM': 20000, 'LOW': 8000},
                            'crack': {'CRITICAL': 80000, 'HIGH': 30000, 'MEDIUM': 15000, 'LOW': 5000},
                            'structural': {'CRITICAL': 150000, 'HIGH': 100000, 'MEDIUM': 50000, 'LOW': 25000},
                            'ok': {'CRITICAL': 0, 'HIGH': 0, 'MEDIUM': 0, 'LOW': 0}
                        }
                        
                        estimated_cost = cost_map.get(label, {'CRITICAL': 5000, 'HIGH': 5000, 'MEDIUM': 3000, 'LOW': 1000}).get(severity, 5000)
                        
                        st.metric("💰 Est. Cost", f"₹{estimated_cost:,}")
                    
                    # Store in session
                    st.session_state['ai_label'] = label
                    st.session_state['ai_severity'] = severity
                    st.session_state['ai_cost'] = estimated_cost
                    
                except Exception as e:
                    st.error(f"AI Error: {e}")
    
    # Save section
    st.markdown("---")
    st.subheader("📝 Review & Save Finding")
    
    col3, col4, col5 = st.columns(3)
    
    with col3:
        final_label = st.selectbox(
            "Issue Type (AI-suggested)",
            ["leak", "crack", "wiring", "structural", "ok"],
            index=["leak", "crack", "wiring", "structural", "ok"].index(
                st.session_state.get('ai_label', 'ok')
            )
        )
    
    with col4:
        final_severity = st.selectbox(
            "Severity (AI-suggested)",
            ["critical", "high", "medium", "low"],
            index=["critical", "high", "medium", "low"].index(
                st.session_state.get('ai_severity', 'low').lower()
            )
        )
    
    with col5:
        final_cost = st.number_input(
            "Repair Cost (₹)",
            min_value=0,
            value=st.session_state.get('ai_cost', 5000),
            step=1000
        )
    
    if st.button("💾 Save AI-Classified Finding", type="primary", use_container_width=True):
        try:
            finding_id = f"F{datetime.now().strftime('%Y%m%d%H%M%S')}"
            room_id = f"R{datetime.now().strftime('%H%M%S')}"
            
            insert_query = f"""
            INSERT INTO HOUSING_INSPECTION.CORE.INSPECTION_FINDINGS 
            (finding_id, room_id, finding_text, image_label, severity, 
             inspection_time, estimated_repair_cost)
            VALUES ('{finding_id}', '{room_id}', '{finding_text}', 
                    '{final_label}', '{final_severity}', 
                    CURRENT_TIMESTAMP(), {final_cost})
            """
            session.sql(insert_query).collect()
            
            st.success(f"✅ Saved with AI classification! Finding ID: {finding_id}")
            st.balloons()
            
        except Exception as e:
            st.error(f"Error: {e}")

# =====================================================
# TAB 3: AI Performance
# =====================================================
with tab3:
    st.header("🤖 AI Classification Performance")
    
    try:
        # Show AI vs Manual comparison
        comparison_query = """
        SELECT
            FINDING_TEXT,
            ORIGINAL_LABEL as MANUAL_LABEL,
            AI_DEFECT_LABEL as AI_LABEL,
            AI_SEVERITY,
            AI_CONFIDENCE_SCORE,
            CASE 
                WHEN ORIGINAL_LABEL = AI_DEFECT_LABEL THEN '✅ Match'
                ELSE '⚠️ Different'
            END as AGREEMENT
        FROM HOUSING_INSPECTION.CORE.AI_DEFECT_INSIGHTS
        """
        
        comp_df = session.sql(comparison_query).to_pandas()
        
        if len(comp_df) > 0:
            col1, col2 = st.columns(2)
            
            with col1:
                st.subheader("📊 AI Accuracy")
                match_pct = (comp_df['AGREEMENT'] == '✅ Match').sum() / len(comp_df) * 100
                st.metric("Agreement with Manual Labels", f"{match_pct:.1f}%")
                
                avg_confidence = comp_df['AI_CONFIDENCE_SCORE'].mean()
                st.metric("Average AI Confidence", f"{avg_confidence:.0f}%")
            
            with col2:
                st.subheader("🎯 Detection Distribution")
                issue_dist = comp_df['AI_LABEL'].value_counts()
                st.bar_chart(issue_dist)
            
            st.markdown("---")
            st.subheader("📋 Detailed AI Classifications")
            st.dataframe(
                comp_df,
                use_container_width=True,
                column_config={
                    "FINDING_TEXT": "Finding",
                    "MANUAL_LABEL": "Manual",
                    "AI_LABEL": "AI Detected",
                    "AI_SEVERITY": "AI Severity",
                    "AI_CONFIDENCE_SCORE": st.column_config.NumberColumn(
                        "Confidence",
                        format="%.0f%%"
                    ),
                    "AGREEMENT": "Match"
                }
            )
        else:
            st.info("No AI classifications yet. Add inspection findings first.")
            
    except Exception as e:
        st.error(f"Error: {e}")

# =====================================================
# TAB 4: All Properties
# =====================================================
with tab4:
    st.header("📋 All Properties Overview")
    
    try:
        all_query = """
        SELECT
            PROPERTY_NAME,
            CITY,
            RISK_LEVEL,
            RISK_SCORE,
            TOTAL_ISSUES,
            TOTAL_ESTIMATED_REPAIR_COST,
            LAST_INSPECTION_TIME,
            CLASSIFICATION_METHOD
        FROM HOUSING_INSPECTION.CORE.STREAMLIT_DASHBOARD_VIEW
        """
        
        all_df = session.sql(all_query).to_pandas()
        
        st.dataframe(
            all_df,
            use_container_width=True,
            column_config={
                "PROPERTY_NAME": "Property",
                "CITY": "City",
                "RISK_LEVEL": "Risk",
                "RISK_SCORE": "Score",
                "TOTAL_ISSUES": "Issues",
                "TOTAL_ESTIMATED_REPAIR_COST": st.column_config.NumberColumn(
                    "Repair Cost",
                    format="₹%d"
                ),
                "LAST_INSPECTION_TIME": st.column_config.DatetimeColumn(
                    "Last Inspection",
                    format="DD/MM/YY HH:mm"
                ),
                "CLASSIFICATION_METHOD": "AI Engine"
            }
        )
        
    except Exception as e:
        st.error(f"Error: {e}")

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #666;'>
    <p>🏗️ <strong>AI-Assisted House Inspection System</strong></p>
    <p>Powered by Snowflake Cortex Intelligence (llama3.1-8b) | AI for Good Initiative</p>
    <p><em>Improving residential safety for families and communities</em></p>
</div>
""", unsafe_allow_html=True)
